name: Application build

on:
  push:
    branches: 
      - main
      - 'v*.*.*'

  pull_request:
    branches:
      - main
      - 'v*.*.*'

jobs:
  rust-build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cargo cache
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-$$ {{ hashFiles('**/Cargo.lock ')}}
          restore-keys: |
            $${{ runner.os }}-cargo-

      - name: Application build
        run: cargo build --verbose

      - name: Application tests
        run: cargo test --verbose

  docker-build-test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: rust-build-test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        name: Login to docker registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract latest tag and branch info
        id: tag_branch_info
        run: |
          # Get the latest Git tag
          tag=$(git describe --tags --abbrev=0 || echo "no-tag")
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
          sanitized_branch=$(echo $branch | sed 's/[^a-zA-Z0-9_\.-]/-/g')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "branch=$sanitized_branch" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v6
        name: build test for docker
        with:
          context: .
          push: false
          tags: ${{ secrets.IMAGE_NAME }}:${{ steps.tag_branch_info.outputs.tag }}-${{ steps.tag_branch_info.outputs.branch }}-${{ github.sha }}

  
  docker-build-and-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: rust-build-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        name: Login to docker registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract latest tag and branch info
        id: tag_branch_info
        run: |
          # Get the latest Git tag
          tag=$(git describe --tags --abbrev=0 || echo "no-tag")
          branch=${GITHUB_REF_NAME}
          sanitized_branch=$(echo $branch | sed 's/[^a-zA-Z0-9_\.-]/-/g')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "branch=$sanitized_branch" >> $GITHUB_OUTPUT
          
      - uses: docker/build-push-action@v6
        name: build and push
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:${{ steps.tag_branch_info.outputs.tag }}-${{ steps.tag_branch_info.outputs.branch }}-${{ github.sha }}

