name: Rust Test, Build, Docker Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ github.sha }} .

      - name: Tag Docker image (latest)
        run: docker tag ${{ secrets.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.IMAGE_NAME }}:latest

      - name: Push Docker image (commit SHA)
        run: docker push ${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Docker image (latest)
        run: docker push ${{ secrets.IMAGE_NAME }}:latest
